version: '3.4'

services:
  sit3232025prac4c:
    image: sit3232025prac4c
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3040:3040
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
