apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
  namespace: default
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # mongoadmin
  mongo-root-password: c2VjcmV0          # secret
